services:
  app:
    build: .
    container_name: nest_app
    restart: always
    env_file:
      - .env
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules # Evita copiar node_modules local para o contêiner
    command: ['npm', 'run', 'start']

  db:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    env_file:
      - .env
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
